import Head from "next/head";
import { SessionProvider } from "next-auth/react";
import "../styles/globals.css";
//, pageProps: { session, ...pageProps }
function MyApp({ Component, pageProps: { session, ...pageProps } }) {
  return (
    <SessionProvider session={pageProps.session}>
      <Head>
        <title>Punktualnik</title>
        <meta name="description" content="Generated by create next app" />
        {/* Bez tego telefon renderuje stronę w wirtualnym oknie 980px i skaluje ją
            w dół — warianty `sm:` odpalały się wtedy TAKŻE na wąskim ekranie, więc
            układy mobilne w kodzie nigdy nie dochodziły do głosu. */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="language" content="Polish" />
        <meta httpEquiv="content-language" content="pl" />
      </Head>
      <Component {...pageProps} />
    </SessionProvider>
  );
}

export default MyApp;
